# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: false
env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
- R -e 'install.packages("http://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_0.12.6.tar.gz", repos = NULL)
