// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// call_stop
void call_stop();
RcppExport SEXP Rcpp_stop_test_call_stop() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call_stop();
    return R_NilValue;
END_RCPP
}
